### ISSUE TITLE
Re-run failed builds automatically

### ISSUE THREAD

**Issue by vtjnash** [JuliaCI/Nanosoldier.jl#101]
Since a few packages have numerically poor tests, it might be helpful (for hiding noisy results) to re-run failing packages to see if they pass.

**Comment by maleadt** [comment]
This is already the case: https://github.com/JuliaCI/PkgEval.jl/blob/972740c66fdd00aeb41524535c2c40c1933c02fa/src/run.jl#L588-L596, in combination with the list in https://github.com/JuliaCI/PkgEval.jl/blob/972740c66fdd00aeb41524535c2c40c1933c02fa/deps/Registries.toml#L18-L29.
