### ISSUE TITLE
Is this README example (about doing a PkgEval assert build) still correct?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaCI/Nanosoldier.jl#105]
The README says:

https://github.com/JuliaCI/Nanosoldier.jl/blob/a2c911a14690cd193faea4e9fd8e1a40c34bd9df/README.md#L184-L188

But is this still correct? Do we still need to pass `USE_BINARYBUILDER_LLVM=0` in order to do an assert build? I thought we pull `LLVM_assert_jll` instead of needing to build LLVM from source?

**Comment by maleadt** [comment]
Ah yes I guess not. I'll update the README

**Comment by DilumAluthge** [comment]
Fixed by https://github.com/JuliaCI/Nanosoldier.jl/commit/9ead85801f8fc3f6018af214010ee3eba413064d?
