### ISSUE TITLE
PkgEvalJob: tests with %self overwrite logs

### ISSUE THREAD

**Issue by maleadt** [JuliaCI/Nanosoldier.jl#108]
https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/7ab26e0_vs_7ab26e0/report.html

**Comment by DilumAluthge** [comment]
It looks like right now, we save each log with a filename of the form `DynamicalSystems.1.8.0-DEV-7ab26e0c85.log`.

Should we instead use filenames of the form `DynamicalSystems.primary.1.8.0-DEV-7ab26e0c85.log` and `DynamicalSystems.against.1.8.0-DEV-7ab26e0c85.log`?

**Comment by maleadt** [comment]
That would probably be the easiest solution. Maybe we can leave the hash out of the filename entirely then?
In addition, we probably want to include some random hash, because otherwise we might be overwriting logs if we re-run (say, with different buildflags).

**Comment by maleadt** [comment]
This should be fixed.
