### ISSUE TITLE
Formatting improvement for benchmark results

### ISSUE THREAD

**Issue by LilithHafner** [JuliaCI/Nanosoldier.jl#111]
Let's say I have [a PR](https://github.com/JuliaLang/julia/pull/45230) which might affect performance, and run a [benchmark job](https://github.com/JuliaCI/NanosoldierReports/blob/master/benchmark/by_hash/2399335_vs_d4acead/report.md).

I don't think there should be regressions, but some plausible regressions are listed. For example,

`["collection", "deletion", ("Set", "Int", "filter!")]` | 1.85 (25%) ❌ | 1.00 (1%)
-- | -- | --

So I reproduce the results locally

```julia
using BaseBenchmarks
BaseBenchmarks.load!("collection")
run(BaseBenchmarks.SUITE["collection"]["deletion"][("Set", "Int", "filter!")])
```

I wish I could copy `["collection"]["deletion"][("Set", "Int", "filter!")]` directly from the results table, rather than replace some of the commas with `][` by hand.

**Comment by vtjnash** [comment]
You can, you are just missing a set of `[]`

**Comment by LilithHafner** [comment]
Thanks!
