### ISSUE TITLE
Test result uploaded wrong results

### ISSUE THREAD

**Issue by LilithHafner** [JuliaCI/Nanosoldier.jl#179]
I tried to [trigger nanosoldier](https://github.com/JuliaLang/julia/pull/44869#issuecomment-1717713494) to run tests for a single package on a custom registry and, 21 minutes later, presumably after running the test I requested, it gave a link to a previous result which took 8 hours to test 8559 packages.

**Comment by LilithHafner** [comment]
The correct results (albeit without appearing to use the custom registry) are here: https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_hash/bf097e2_vs_15b590b/report.md

**Comment by maleadt** [comment]
Note that reports can overwrite, https://github.com/JuliaCI/Nanosoldier.jl/issues/83

**Comment by LilithHafner** [comment]
Strange, in addition to #83, it seems that the second time I invoked nanosoldier, it used the same comparison build as the first, even though master had updated in the intervening four days.

**Comment by maleadt** [comment]
> Strange, in addition to #83, it seems that the second time I invoked nanosoldier, it used the same comparison build as the first, even though master had updated in the intervening four days.

Did your branch update in the meantime? Nanosoldier uses the merge-base of your branch, not simply master, as that may otherwise lead to results that are hard to compare wrt. the diff of the PR.

(Well, only the PkgEval bot does, because the Benchmarks one hasn't been updated in a while, but that's a separate issue)

**Comment by LilithHafner** [comment]
That makes sense and is good behavior. In that case, this is a duplicate of #83.
