### ISSUE TITLE
Auto-delete old directories of failed builds

### ISSUE THREAD

**Issue by jrevels** [JuliaCI/Nanosoldier.jl#19]
Currently, a [build directories only gets cleaned up if the benchmark job completes without error](https://github.com/JuliaCI/Nanosoldier.jl/blob/master/src/jobs/BenchmarkJob.jl#L376). This was originally intentional, as it aided in debugging job failures. However, this is no longer necessary since [relevant build logs will now get uploaded to BaseBenchmarkReports](https://github.com/JuliaCI/Nanosoldier.jl#benchmark-results) even if the job doesn't finish.

**Comment by vtjnash** [comment]
For better or worse, since v1.5, Julia now periodically auto-deletes old directories of failed builds

**Comment by vtjnash** [comment]
Refs https://github.com/JuliaLang/julia/pull/32851
