### ISSUE TITLE
Make all server logs publicly available

### ISSUE THREAD

**Issue by jrevels** [JuliaCI/Nanosoldier.jl#20]
- [ ] Messages written by a benchmark job via [`nodelog`](https://github.com/JuliaCI/Nanosoldier.jl/blob/master/src/config.jl#L44) should be uploaded along with the rest of a benchmark job's logs. 
- [ ] All the server logs (`node*.log` files) that currently reside on the cluster should be uploaded publicly to a single location. Every time Nanosoldier completes a job, it could update the public versions of these files. 
- [ ] We should capture and publicly upload the output of the tmux window in which the head node of the server runs. We'd have to be careful to ensure this output doesn't leak private info like auth keys.
- [ ] We should probably implement a clean-up pass which deletes log messages that are over a week old.

**Comment by vtjnash** [comment]
I'm going to claim this is not necessary, since it has been many years now. These logs are more likely to contain private info, while the build logs should be sufficient.
