### ISSUE TITLE
Auto-restart Nanosoldier if it falls over

### ISSUE THREAD

**Issue by jrevels** [JuliaCI/Nanosoldier.jl#21]
Currently, uncaught server errors or external errors in the julia process will cause Nanosoldier to fall over, at which point it needs to be manually restarted. 

The first solution that comes to my mind would be for Nanosoldier to deliver a heartbeat every `X` minutes (maybe just by logging a timestamp to a file), and a separate cronjob which verifies the heartbeat. If the heartbeat is too old/invalid, the cronjob kills any existing server processes and spins up a new server process.

EDIT: Additionally, the cronjob could email myself or another maintainer with a bug report (tmux capture/server logs at the time of failure). Or, if we want to get fancy, it could automatically open an issue for the failure on GitHub.

**Comment by maleadt** [comment]
This can be solved by running under a service manager, as is e.g. done with the PkgEval bot (which runs under systemd).
