### ISSUE TITLE
Add functionality for automating the BaseBenchmarks tuning process

### ISSUE THREAD

**Issue by jrevels** [JuliaCI/Nanosoldier.jl#22]
Currently, a [tuning process](https://github.com/JuliaCI/BaseBenchmarks.jl/blob/master/etc/tune.jl#L30) must be manually run whenever new benchmarks are added to BaseBenchmarks, or when changes to Julia invalidate the cached parameters. Nanosoldier can and should automate this process. 

The process that needs to be automated is:
1. Build Julia
2. Pull BaseBenchmarks `master`
3. Run the tuning script
4. Commit and upload the new parameters to `master`
5. Rebase BaseBenchmarks' `nanosoldier` branch on top of the new `master`.

This process should be structured as a new `J<:AbstractJob` type that can be triggered via Nanosoldier's comment syntax (e.g. `tunebenchmarks(...)`). The same cron script that submits the daily benchmark job should be modified to submit a daily retuning job.

**Comment by tkelman** [comment]
(canonicalized link in case line numbers or file organization changes: https://github.com/JuliaCI/BaseBenchmarks.jl/blob/065fc5cc37e5c0b5df10dced29992db91e6defde/etc/tune.jl#L30)

**Comment by simonbyrne** [comment]
Do the parameters need to be on `master`? Couldn't you just have them on the `nanosoldier` branch? i.e.
```
git checkout nanosoldier
git merge master
[rerun benchmarks]
git add etc/params.jld
git commit 
git push origin nanosoldier
```

This is probably slightly safer if the process is to be automated, as you don't have a bot pushing to  `master`.

**Comment by ararslan** [comment]
> Do the parameters need to be on master?

At least one of the tests in BaseBenchmarks assumes that the params file exists, but presumably we could find another way to structure the tests.

**Comment by vtjnash** [comment]
There's a github action now for this
