### ISSUE TITLE
stop abusing git for timing data storage

### ISSUE THREAD

**Issue by jrevels** [JuliaCI/Nanosoldier.jl#36]
Should've made this issue a long time ago.

Each Nanosoldier run generates a fair amount of timing data, which is currently stored in https://github.com/JuliaCI/BaseBenchmarkReports. [As was discussed way back in the early days of Nanosoldier](https://github.com/JuliaLang/julia/issues/13893#issuecomment-225365222), this is a pretty gross abuse of git/GitHub. 

We could instead just dump the data on a publicly accessible filesystem (and eventually, let the data be ingested by a more granularly queryable database).

While not directly tied to this issue, it'd also be nice to tackle the old [lightweight/stable/portable serialization issue](https://github.com/JuliaCI/BenchmarkTools.jl/issues/15) at the same time. It should be simple enough to write a JSON (de)serializer for the list of ([benchmark key](https://github.com/JuliaCI/BenchmarkTools.jl/blob/master/doc/manual.md#indexing-into-a-benchmarkgroup-using-a-vector), [`BenchmarkTools.Trial`](https://github.com/JuliaCI/BenchmarkTools.jl/blob/1238af0326a13f44c2121a017a13e7ef327bddf6/src/trials.jl#L5)) pairs you'd need to store.

**Comment by simonbyrne** [comment]
What about sticking it in some cloud nosql store (DynamoDB, BigTable, etc.)?

**Comment by StefanKarpinski** [comment]
How about producing CSV and pushing it to S3?

**Comment by jrevels** [comment]
> How about producing CSV and pushing it to S3?

The data's not well structured for CSV (AFAICT you'd have to have many, many smallish files), but yeah, any simple storage solution should work fine for this to start.

**Comment by vtjnash** [comment]
The json files compress well (e.g. https://github.com/JuliaCI/BenchmarkTools.jl/pull/79), so while we have generated a lot of data, and may want to add a TSDB for other reasons, the current rate of growth isn't terrible:
```
$ du -sh NanosoldierReports/
13G     NanosoldierReports/
$ du -sh NanosoldierReports/.git
5.8G    NanosoldierReports/.git

$ du -sh NanosoldierReports/pkgeval/by_date/latest/
11M     NanosoldierReports/pkgeval/by_date/latest/

$ du -sh NanosoldierReports/benchmark/by_date/2021-02/17/
7.4M    NanosoldierReports/benchmark/by_date/2021-02/17/
```

What might make the most difference is doing each by_date run as an update to `latest` directly (instead of keeping each copy in a folder). That would make the most use of git's abilities to compare logs and delta-compress changes.

**Comment by KristofferC** [comment]
I kind of doubt the value in saving the timing data for each trial and think it is enough to save the statistics. Sure, people said some years ago that someone maybe would want to do some analysis on the data but looking at the activity in these reports, I doubt that will happen, nor bring anything actionable for old runs.

**Comment by vtjnash** [comment]
The isdaily reports are generated from the data.tar.xz files

**Comment by KristofferC** [comment]
Yes, in there is a ~500 MB json file in there that contains the timing for every sample for every benchmark. I don't think anything has been done with those trial timings other than computing the minimum of it. So I am saying to just store e.g. the minimum and reduce the file size by a couple of order of magnitudes.

**Comment by maleadt** [comment]
[Actual timing data isn't stored anymore.](https://github.com/JuliaCI/Nanosoldier.jl/pull/121)
