### ISSUE TITLE
Should regressing/improving tests be re-run?

### ISSUE THREAD

**Issue by jrevels** [JuliaCI/Nanosoldier.jl#4]
moved from JuliaCI/BenchmarkTools.jl#10

> Given the large number of tests, there is still a fair amount of noise in the reports. It would seem that one way to reduce the noise would be to follow up on apparent regressions/improvements with a re-running of those tests. I haven't looked into the infrastructure at all to see how easy this would be, but if both builds are still available I'm wondering whether this would be fairly straightforward?

**Comment by jrevels** [comment]
> Given the large number of tests, there is still a fair amount of noise in the reports

@timholy Can you show some examples of which reports didn't match your local results? I haven't had time to keep up with new reports in my day-to-day since writing code for benchmark CI became a spare-time project rather than a work project. 

I do a fair amount of manual experimentation for each deployment, and from what I've seen the false regression/improvement rate is slightly less than one benchmark per benchmark job. Does that match up with what you see? For example, [this is one of the fake PRs I set up to test for invariance](https://github.com/jrevels/julia/pull/5). I've done a bit more testing than just that PR, but you get the idea.

I do like the idea of automatically gathering more samples for benchmarks which demonstrate changes.

**Comment by timholy** [comment]
I should check more, but often I see ~15% for things that seemingly shouldn't be affected. I'll check more carefully on a more limited PR sometime.

**Comment by timholy** [comment]
After building two copies of julia, one for my PR and one for master, and always running them side-by-side, I agree more with nanosoldier. So I no longer think this is necessary.
