### ISSUE TITLE
Race conditions

### ISSUE THREAD

**Issue by mbauman** [JuliaCI/Nanosoldier.jl#48]
It appears as though the exact versions that get compared depend upon the time they get started.  This can lead to unrelated commits getting involved in the comparison.  Based purely upon the behavior I've seen in the reported logs, it appears as though the following things occur:

* Job gets submitted
* Nanosoldier begins building master, grabbing the tip of the master at the time the build starts
* Nanosoldier begins building the merge of the PR, grabbing the tip of the master and the tip of the PR branch at the time _this_ build starts

This can lead to the PR build having extra, unexpected commits in its history, both from the master and PR branch (although the latter can actually work in our favor given the long lead time).  Ideally, we'd just figure out the master and the PR merge hashes immediately upon submission to avoid these problems.

**Comment by vchuravy** [comment]
Hm cursory glancing at the code I think the race condition comes from https://github.com/JuliaCI/Nanosoldier.jl/blob/9f04e2fee6d4bb27504a687f65771e3e65d7739f/src/build.jl#L34 and https://github.com/JuliaCI/Nanosoldier.jl/blob/9f04e2fee6d4bb27504a687f65771e3e65d7739f/src/jobs/BenchmarkJob.jl#L62 The latter is setting the the versus to the at the time current master sha, and the former is getting the merge commit at a later point.

**Comment by jrevels** [comment]
Yeah, the git fetches in `build_julia!` just need to be moved into the `BenchmarkJob` constructor

**Comment by maleadt** [comment]
Fixed in https://github.com/JuliaCI/Nanosoldier.jl/pull/134; the BenchmarkJob constructor now determines what to test, and `build.jl` only checks out the configured sha.
