### ISSUE TITLE
Fix the periodic "too many open files" error

### ISSUE THREAD

**Issue by ararslan** [JuliaCI/Nanosoldier.jl#60]
More often than not, if the server isn't responding, it's because it hit a `Base.IOError("getaddrinfo: too many open files (EMFILE)", -24)`. I'm not sure why this happens but my best guess is that the log files that are `open`ed aren't getting properly `close`d somewhere.

**Comment by ararslan** [comment]
#61 should hopefully fix this. Once the server is updated with that fix, if we go a long time without seeing the error then I'll just close this.

**Comment by vtjnash** [comment]
I'll assume this is fixed then
