### ISSUE TITLE
Slight rephrasing of Nanosoldier comment?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaCI/Nanosoldier.jl#67]
When Nanosoldier finishes a benchmark job, it posts this comment: ([example](https://github.com/JuliaLang/julia/commit/c2abaeedf8316a392035ff63fa6460595a9a5dd3#commitcomment-36927534))
> Your benchmark job has completed - possible performance regressions were detected. A full report can be found here. cc @ararslan

The text makes it clear that this is regarding a benchmark job to look for performance regressions.

---

When Nanosoldier finishes a PkgEval job, it posts this comment: ([example](https://github.com/JuliaLang/julia/commit/c2abaeedf8316a392035ff63fa6460595a9a5dd3#commitcomment-36926090))
> Your test job has completed - possible new issues were detected. A full report can be found here. cc @maleadt

It is not immediately obvious to me that this is regarding a PkgEval run. "Test job" is pretty nonspecific. Maybe we can modify the wording to say:
> Your PkgEval test job has completed - possible new issues were detected

cc: @maleadt

**Comment by maleadt** [comment]
Sure, sounds good.
