### ISSUE TITLE
avoid updating 'latest' link when PkgEval fails?

### ISSUE THREAD

**Issue by vtjnash** [JuliaCI/Nanosoldier.jl#90]
If the 'latest' link gets updated, then we then lose out on the comparison diff being created for several days. For example: https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_date/2021-04/01/report.md

So we should probably have 'latest' stay pointing at the last-known-good run instead (@maleadt).

**Comment by maleadt** [comment]
Sounds reasonable. I've created a PR.
